typeset -g POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# Clean, minimal layout
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status context time)

typeset -g POWERLEVEL9K_BACKGROUND=''
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '

typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=false
typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=''

# Directory
typeset -g POWERLEVEL9K_DIR_FOREGROUND=white
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=white
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=white
typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=true
typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=0

# Status
typeset -g POWERLEVEL9K_STATUS_OK=true
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=green
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=red
typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✓'
typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✗'
typeset -g POWERLEVEL9K_STATUS_CONTENT_EXPANSION=''

# User@host
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=cyan
typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
typeset -g POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true
typeset -g POWERLEVEL9K_CONTEXT_VISUAL_IDENTIFIER_EXPANSION=''

# Time
typeset -g POWERLEVEL9K_TIME_FOREGROUND=yellow
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%I:%M:%S %p}'
typeset -g POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=true

# No extra newline
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
